# Generated by Django 6.0.1 on 2026-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
