# Generated by Django 6.0.1 on 2026-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_service_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
