# Generated by Django 6.0.1 on 2026-02-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_service_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verification_letter',
            field=models.FileField(blank=True, null=True, upload_to='org_letters/'),
        ),
    ]
