# Generated by Django 6.0.1 on 2026-01-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_volunteerprofile_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.AddField(
            model_name='application',
            name='submission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SELECTED', 'Selected'), ('COMPLETED', 'Completed')], default='APPLIED', max_length=20),
        ),
    ]
