# Generated by Django 6.0.1 on 2026-02-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_organization_verification_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to='service_letters/'),
        ),
    ]
