# Generated by Django 6.0.1 on 2026-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
