# Generated by Django 6.0.1 on 2026-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_application_rating_application_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerprofile',
            old_name='year_of_study',
            new_name='year',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='email',
            field=models.EmailField(default='temp@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='full_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.TextField(),
        ),
    ]
