# Generated by Django 5.2.4 on 2026-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_service_date_service_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateField(),
        ),
    ]
