# Generated by Django 5.2.4 on 2026-02-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_service_end_date_alter_service_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='required_volunteers',
        ),
        migrations.AddField(
            model_name='service',
            name='max_volunteers',
            field=models.IntegerField(default=10),
        ),
    ]
