# Generated by Django 6.0.1 on 2026-01-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_year_of_study_volunteerprofile_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='email',
        ),
    ]
