# Generated by Django 5.2.4 on 2026-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_service_required_volunteers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_volunteers',
            field=models.IntegerField(),
        ),
    ]
