# Generated by Django 6.0.1 on 2026-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_volunteerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
