# Generated by Django 5.2.4 on 2026-02-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_service_max_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='APPLIED', max_length=20),
        ),
    ]
