# Generated by Django 6.0.1 on 2026-02-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_volunteerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_gender',
            field=models.CharField(choices=[('ANY', 'Any'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='ANY', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='required_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
