# Generated by Django 6.0.1 on 2026-02-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_service_required_gender_service_required_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SELECTED', 'Selected'), ('WAITLIST', 'Waitlist'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='APPLIED', max_length=20),
        ),
    ]
