# Generated by Django 6.0.1 on 2026-02-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='absence_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='absence_requested',
            field=models.BooleanField(default=False),
        ),
    ]
