# Generated by Django 6.0.1 on 2026-02-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_application_absence_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SELECTED', 'Selected'), ('WAITLIST', 'Waitlist'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('ABSENT', 'Absent')], default='APPLIED', max_length=20),
        ),
    ]
