# Generated by Django 6.0.1 on 2026-02-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_organization_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='org_covers/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
