# Generated by Django 6.0.1 on 2026-02-24 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_organization_cover_image_organization_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='promo_video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='OrganizationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='org_gallery/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.organization')),
            ],
        ),
    ]
