# Generated by Django 5.2.4 on 2026-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_notification'),
        ('app1', '0018_alter_organization_website'),
    ]

    operations = [
    ]
