# Generated by Django 5.2.4 on 2026-02-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_notification_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='app1.service')),
            ],
        ),
    ]
