# Generated by Django 5.2.4 on 2026-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_servicecoordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
