# Generated by Django 5.2.4 on 2026-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_service_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='coordinators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='ServiceCoordinator',
        ),
    ]
