# Generated by Django 5.2.4 on 2026-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
